fun main() {

// Examble ArithmeticException (1)

    var a = 5
    var b = 0
    println(a/b)

/* Ans: Exception happened when we have division "a" on "b",
   which "b" equal zero, meaning that the value of an operation will give infinite number,
   this gives me an exception Type of  */

}
